# Generated by Django 4.2.3 on 2023-08-04 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='connected_habit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='habits.habit'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='sign',
            field=models.BooleanField(default=False, verbose_name='признак приятной привычки'),
        ),
    ]
