# Generated by Django 4.2.3 on 2023-08-04 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_alter_habit_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='periodicity',
            field=models.IntegerField(choices=[(1, 'everyday'), (2, 'twice a week'), (3, 'thrice a week')], verbose_name='периодичность'),
        ),
    ]
