# Generated by Django 4.2.3 on 2023-08-04 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_alter_habit_periodicity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='reward',
            field=models.CharField(blank=True, null=True, verbose_name='награда'),
        ),
    ]
